name: 'Calculate versions for TMP components'
description: 'Calculates the next production and beta versions'
author: 'The Money Platform'

# Define your inputs here.
inputs:
  release-level:
    description: 'The release level'
    required: true
    default: 'patch'
  latest-production-version:
    description: 'The latest production version'
    required: true
    default: 'v0.0.0'
  latest-beta-version:
    description: 'The latest beta version'
    required: false
    default: 'v0.0.0-beta.1'

# Define your outputs here.
outputs:
  next-production-version:
    description: 'The next production version'
  next-beta-version:
    description: 'The next beta version'

runs:
  using: node20
  main: dist/index.js
